openapi: 3.2.0
info:
  title: ITCollect Public By 2026 Variance Scores Count Report API
  version: 0.1-beta
  description: 'The IT Dashboard team aims to build a modern API that acts as the center-piece of a modular IT data reporting ecosystem. This OpenAPI spec shows the initial direction of ITCollect Public data architecture for budget year 2026, and it is aimed at providing real-time updates to the IT Collect Public By 2026 API. It will serve as living documentation of the latest changes.


    In order to access ITCollect Public Api, Please fill out the below form to obtain an authorization key


    Loading signup form...'
  x-logo:
    url: images/logo-gsa.svg
    backgroundColor: '#FFFFFF'
    altText: U.S General Services Administration
servers:
- url: /
  description: ''
tags:
- name: VarianceScoresCountReport
paths:
  /v1/reports/variance-scores:
    parameters: []
    get:
      operationId: getVarianceScoresCountReportCollection
      tags:
      - VarianceScoresCountReport
      responses:
        '200':
          description: VarianceScoresCountReport collection
          content:
            application/ld+json:
              schema:
                type: object
                properties:
                  hydra:member:
                    type: array
                    items:
                      $ref: '#/components/schemas/VarianceScoresCountReport.jsonld-varianceScoresCount'
                  hydra:totalItems:
                    type: integer
                    minimum: 0
                  hydra:view:
                    type: object
                    properties:
                      '@id':
                        type: string
                        format: string
                      '@type':
                        type: string
                      hydra:first:
                        example: ../page=1
                        type: string
                        format: string
                      hydra:last:
                        example: ../page=200
                        type: string
                        format: string
                      hydra:previous:
                        example: ../page=0
                        type: string
                        format: string
                      hydra:next:
                        example: ../page=2
                        type: string
                        format: string
                  hydra:search:
                    type: object
                    properties:
                      '@type':
                        type: string
                      hydra:template:
                        type: string
                      hydra:variableRepresentation:
                        type: string
                      hydra:mapping:
                        type: array
                        items:
                          type: object
                          properties:
                            '@type':
                              type: string
                            variable:
                              type: string
                            property:
                              type:
                              - string
                              - 'null'
                            required:
                              type: boolean
                required:
                - hydra:member
        '400':
          description: Bad Request
          content:
            application/ld+json:
              schema:
                type: object
                properties:
                  '@context':
                    type: string
                    example: /contexts/ConstraintViolationList
                  '@type':
                    type: string
                    example: ConstraintViolationList
                  hydra:title:
                    type: string
                    example: Validation Errors Encountered
                  hydra:description:
                    type: string
                    example: Found `2` constraint violations
                  violations:
                    type: array
                    items:
                    - type: object
                      properties:
                        propertyPath:
                          type: string
                          example: propertyName
                        message:
                          type: string
                          example: Sample error message 1
                        code:
                          type: string
                          example: 25c84bec-2466-47ba-83d2-3b7243593897
                    - type: object
                      properties:
                        propertyPath:
                          type: string
                          example: propertyName
                        message:
                          type: string
                          example: Sample error message 2
                        code:
                          type: string
                          example: 70bafca1-5975-4171-92cc-e3cdde9b4b7d
                  hydra:request_id:
                    type: string
                    example: xzf6bgh6-8ba2-83jn-p5a1-e4ac0f74nf5g
            application/json:
              schema:
                type: object
                properties:
                  '@context':
                    type: string
                    example: /contexts/ConstraintViolationList
                  '@type':
                    type: string
                    example: ConstraintViolationList
                  hydra:title:
                    type: string
                    example: Validation Errors Encountered
                  hydra:description:
                    type: string
                    example: Found `2` constraint violations
                  violations:
                    type: array
                    items:
                    - type: object
                      properties:
                        propertyPath:
                          type: string
                          example: propertyName
                        message:
                          type: string
                          example: Sample error message 1
                        code:
                          type: string
                          example: 25c84bec-2466-47ba-83d2-3b7243593897
                    - type: object
                      properties:
                        propertyPath:
                          type: string
                          example: propertyName
                        message:
                          type: string
                          example: Sample error message 2
                        code:
                          type: string
                          example: 70bafca1-5975-4171-92cc-e3cdde9b4b7d
                  hydra:request_id:
                    type: string
                    example: xzf6bgh6-8ba2-83jn-p5a1-e4ac0f74nf5g
        '404':
          description: Resource Not Found
          content:
            application/ld+json:
              schema:
                type: object
                properties:
                  '@context':
                    type: string
                    example: /contexts/Error
                  '@type':
                    type: string
                    example: hydra:Error
                  hydra:title:
                    type: string
                    example: NotFoundHttpException
                  hydra:description:
                    type: string
                    example: Not Found
                  hydra:request_id:
                    type: string
                    example: xzf6bgh6-8ba2-83jn-p5a1-e4ac0f74nf5g
            application/json:
              schema:
                type: object
                properties:
                  '@context':
                    type: string
                    example: /contexts/Error
                  '@type':
                    type: string
                    example: hydra:Error
                  hydra:title:
                    type: string
                    example: NotFoundHttpException
                  hydra:description:
                    type: string
                    example: Not Found
                  hydra:request_id:
                    type: string
                    example: xzf6bgh6-8ba2-83jn-p5a1-e4ac0f74nf5g
        '406':
          description: Unsupported Media Type
          content:
            application/ld+json:
              schema:
                type: object
                properties:
                  '@context':
                    type: string
                    example: /contexts/Error
                  '@type':
                    type: string
                    example: hydra:Error
                  hydra:title:
                    type: string
                    example: UnsupportedMediaTypeHttpException
                  hydra:description:
                    type: string
                    example:
                      Unsupported Media Type:
                        The provided content-type is not supported, Supported MIME types are:
                          POST/PUT/DELETE: application/json, or application/ld+json
                          PATCH: application/merge-patch+json
                          GET: application/json, application/ld+json, or text/csv
                  hydra:request_id:
                    type: string
                    example: xzf6bgh6-8ba2-83jn-p5a1-e4ac0f74nf5g
            application/json:
              schema:
                type: object
                properties:
                  '@context':
                    type: string
                    example: /contexts/Error
                  '@type':
                    type: string
                    example: hydra:Error
                  hydra:title:
                    type: string
                    example: UnsupportedMediaTypeHttpException
                  hydra:description:
                    type: string
                    example:
                      Unsupported Media Type:
                        The provided content-type is not supported, Supported MIME types are:
                          POST/PUT/DELETE: application/json, or application/ld+json
                          PATCH: application/merge-patch+json
                          GET: application/json, application/ld+json, or text/csv
                  hydra:request_id:
                    type: string
                    example: xzf6bgh6-8ba2-83jn-p5a1-e4ac0f74nf5g
        '500':
          description: Internal Server Error
          content:
            application/ld+json:
              schema:
                type: object
                properties:
                  '@context':
                    type: string
                    example: /contexts/Error
                  '@type':
                    type: string
                    example: hydra:Error
                  hydra:title:
                    type: string
                    example: InternalServerErrorException
                  hydra:description:
                    type: string
                    example: Internal Server Error
                  hydra:request_id:
                    type: string
                    example: xzf6bgh6-8ba2-83jn-p5a1-e4ac0f74nf5g
            application/json:
              schema:
                type: object
                properties:
                  '@context':
                    type: string
                    example: /contexts/Error
                  '@type':
                    type: string
                    example: hydra:Error
                  hydra:title:
                    type: string
                    example: InternalServerErrorException
                  hydra:description:
                    type: string
                    example: Internal Server Error
                  hydra:request_id:
                    type: string
                    example: xzf6bgh6-8ba2-83jn-p5a1-e4ac0f74nf5g
      summary: Retrieves the collection of VarianceScoresCountReport resources
      description: Retrieves the collection of VarianceScoresCountReport resources.
      parameters:
      - name: currentUII
        in: query
        description: Current UII of the service
        required: false
        deprecated: false
        allowEmptyValue: false
        schema:
          type: string
        style: form
        explode: false
        allowReserved: false
      - name: projectStatus
        in: query
        description: Display variance scores based on project status
        required: false
        deprecated: false
        allowEmptyValue: false
        schema:
          type: string
          enum:
          - Not Started
          - In progress
          - Completed
          - Deferred
          - Canceled
        style: form
        explode: false
        allowReserved: false
      - name: agency
        in: query
        description: Three digit agency code of the UII.
        required: false
        deprecated: false
        allowEmptyValue: false
        schema:
          type: string
          enum:
          - '005'
          - '006'
          - '007'
          - 008
          - 009
          - '010'
          - '011'
          - '012'
          - '013'
          - '014'
          - '015'
          - '016'
          - 018
          - 019
          - '020'
          - '021'
          - '022'
          - '023'
          - '024'
          - '025'
          - '026'
          - '027'
          - 028
          - 029
          - '184'
          - '202'
          - '393'
          - '422'
          - '429'
        style: form
        explode: false
        allowReserved: false
      deprecated: false
components:
  schemas:
    VarianceScoresCountReport.jsonld-varianceScoresCount:
      type: object
      description: ''
      additionalProperties: false
      properties:
        '@id':
          readOnly: true
          type: string
        '@type':
          readOnly: true
          type: string
        agency:
          readOnly: true
          description: The three digit agency code.
          type: string
        projectsWithLowCostVariance:
          type: number
          format: integer
          example: 1
          readOnly: true
          description: 'Total Count of Cost Variance Scores between: -10% and 10%'
        projectsWithMediumCostVariance:
          type: number
          format: integer
          example: 1
          readOnly: true
          description: 'Total Count of Cost Variance Scores between: -30% and -10% OR 10% and 30%'
        projectsWithHighCostVariance:
          type: number
          format: integer
          example: 1
          readOnly: true
          description: Total Count of Cost Variance Scores less than -30% OR greater than 30%
        projectsWithLowScheduleVariance:
          type: number
          format: integer
          example: 1
          readOnly: true
          description: 'Total Count of Schedule Variance Scores between: -10% and 10%'
        projectsWithMediumScheduleVariance:
          type:
          - number
          - 'null'
          format: integer
          example: 1
          readOnly: true
          description: 'Total Count of Schedule Variance Scores between: -30% and -10% OR 10% and 30%'
        projectsWithHighScheduleVariance:
          type:
          - number
          - 'null'
          format: integer
          example: 1
          readOnly: true
          description: Total Count of Schedule Variance Scores less than -30% OR greater than 30%
