openapi: 3.2.0
info:
  title: ITCollect Public By 2026 Supplemental Services Feed API
  version: 0.1-beta
  description: 'The IT Dashboard team aims to build a modern API that acts as the center-piece of a modular IT data reporting ecosystem. This OpenAPI spec shows the initial direction of ITCollect Public data architecture for budget year 2026, and it is aimed at providing real-time updates to the IT Collect Public By 2026 API. It will serve as living documentation of the latest changes.


    In order to access ITCollect Public Api, Please fill out the below form to obtain an authorization key


    Loading signup form...'
  x-logo:
    url: images/logo-gsa.svg
    backgroundColor: '#FFFFFF'
    altText: U.S General Services Administration
servers:
- url: /
  description: ''
tags:
- name: SupplementalServicesFeed
paths:
  /v1/feeds/reports/supplemental-services-feed:
    parameters: []
    get:
      operationId: getSupplementalServicesFeedCollection
      tags:
      - SupplementalServicesFeed
      responses:
        '200':
          description: SupplementalServicesFeed collection
          content:
            application/ld+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SupplementalServicesFeed-supplementalServicesFeed_supService'
            text/csv:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SupplementalServicesFeed-supplementalServicesFeed_supService'
        '400':
          description: Bad Request
          content:
            application/ld+json:
              schema:
                type: object
                properties:
                  '@context':
                    type: string
                    example: /contexts/ConstraintViolationList
                  '@type':
                    type: string
                    example: ConstraintViolationList
                  hydra:title:
                    type: string
                    example: Validation Errors Encountered
                  hydra:description:
                    type: string
                    example: Found `2` constraint violations
                  violations:
                    type: array
                    items:
                    - type: object
                      properties:
                        propertyPath:
                          type: string
                          example: propertyName
                        message:
                          type: string
                          example: Sample error message 1
                        code:
                          type: string
                          example: 25c84bec-2466-47ba-83d2-3b7243593897
                    - type: object
                      properties:
                        propertyPath:
                          type: string
                          example: propertyName
                        message:
                          type: string
                          example: Sample error message 2
                        code:
                          type: string
                          example: 70bafca1-5975-4171-92cc-e3cdde9b4b7d
                  hydra:request_id:
                    type: string
                    example: xzf6bgh6-8ba2-83jn-p5a1-e4ac0f74nf5g
            application/json:
              schema:
                type: object
                properties:
                  '@context':
                    type: string
                    example: /contexts/ConstraintViolationList
                  '@type':
                    type: string
                    example: ConstraintViolationList
                  hydra:title:
                    type: string
                    example: Validation Errors Encountered
                  hydra:description:
                    type: string
                    example: Found `2` constraint violations
                  violations:
                    type: array
                    items:
                    - type: object
                      properties:
                        propertyPath:
                          type: string
                          example: propertyName
                        message:
                          type: string
                          example: Sample error message 1
                        code:
                          type: string
                          example: 25c84bec-2466-47ba-83d2-3b7243593897
                    - type: object
                      properties:
                        propertyPath:
                          type: string
                          example: propertyName
                        message:
                          type: string
                          example: Sample error message 2
                        code:
                          type: string
                          example: 70bafca1-5975-4171-92cc-e3cdde9b4b7d
                  hydra:request_id:
                    type: string
                    example: xzf6bgh6-8ba2-83jn-p5a1-e4ac0f74nf5g
        '404':
          description: Resource Not Found
          content:
            application/ld+json:
              schema:
                type: object
                properties:
                  '@context':
                    type: string
                    example: /contexts/Error
                  '@type':
                    type: string
                    example: hydra:Error
                  hydra:title:
                    type: string
                    example: NotFoundHttpException
                  hydra:description:
                    type: string
                    example: Not Found
                  hydra:request_id:
                    type: string
                    example: xzf6bgh6-8ba2-83jn-p5a1-e4ac0f74nf5g
            application/json:
              schema:
                type: object
                properties:
                  '@context':
                    type: string
                    example: /contexts/Error
                  '@type':
                    type: string
                    example: hydra:Error
                  hydra:title:
                    type: string
                    example: NotFoundHttpException
                  hydra:description:
                    type: string
                    example: Not Found
                  hydra:request_id:
                    type: string
                    example: xzf6bgh6-8ba2-83jn-p5a1-e4ac0f74nf5g
        '406':
          description: Unsupported Media Type
          content:
            application/ld+json:
              schema:
                type: object
                properties:
                  '@context':
                    type: string
                    example: /contexts/Error
                  '@type':
                    type: string
                    example: hydra:Error
                  hydra:title:
                    type: string
                    example: UnsupportedMediaTypeHttpException
                  hydra:description:
                    type: string
                    example:
                      Unsupported Media Type:
                        The provided content-type is not supported, Supported MIME types are:
                          POST/PUT/DELETE: application/json, or application/ld+json
                          PATCH: application/merge-patch+json
                          GET: application/json, application/ld+json, or text/csv
                  hydra:request_id:
                    type: string
                    example: xzf6bgh6-8ba2-83jn-p5a1-e4ac0f74nf5g
            application/json:
              schema:
                type: object
                properties:
                  '@context':
                    type: string
                    example: /contexts/Error
                  '@type':
                    type: string
                    example: hydra:Error
                  hydra:title:
                    type: string
                    example: UnsupportedMediaTypeHttpException
                  hydra:description:
                    type: string
                    example:
                      Unsupported Media Type:
                        The provided content-type is not supported, Supported MIME types are:
                          POST/PUT/DELETE: application/json, or application/ld+json
                          PATCH: application/merge-patch+json
                          GET: application/json, application/ld+json, or text/csv
                  hydra:request_id:
                    type: string
                    example: xzf6bgh6-8ba2-83jn-p5a1-e4ac0f74nf5g
        '500':
          description: Internal Server Error
          content:
            application/ld+json:
              schema:
                type: object
                properties:
                  '@context':
                    type: string
                    example: /contexts/Error
                  '@type':
                    type: string
                    example: hydra:Error
                  hydra:title:
                    type: string
                    example: InternalServerErrorException
                  hydra:description:
                    type: string
                    example: Internal Server Error
                  hydra:request_id:
                    type: string
                    example: xzf6bgh6-8ba2-83jn-p5a1-e4ac0f74nf5g
            application/json:
              schema:
                type: object
                properties:
                  '@context':
                    type: string
                    example: /contexts/Error
                  '@type':
                    type: string
                    example: hydra:Error
                  hydra:title:
                    type: string
                    example: InternalServerErrorException
                  hydra:description:
                    type: string
                    example: Internal Server Error
                  hydra:request_id:
                    type: string
                    example: xzf6bgh6-8ba2-83jn-p5a1-e4ac0f74nf5g
      summary: Retrieves the collection of SupplementalServicesFeed resources
      description: Retrieves the collection of SupplementalServicesFeed resources.
      parameters:
      - name: page
        in: query
        description: The collection page number
        required: false
        deprecated: false
        allowEmptyValue: true
        schema:
          type: integer
          default: 1
        style: form
        explode: false
        allowReserved: false
      - name: agencyId
        in: query
        description: ''
        required: false
        deprecated: false
        allowEmptyValue: true
        schema:
          type: string
        style: form
        explode: false
        allowReserved: false
      - name: agencyId[]
        in: query
        description: ''
        required: false
        deprecated: false
        allowEmptyValue: true
        schema:
          type: array
          items:
            type: string
        style: form
        explode: true
        allowReserved: false
      - name: sort[lastModified]
        in: query
        description: ''
        required: false
        deprecated: false
        allowEmptyValue: true
        schema:
          type: string
          enum:
          - asc
          - desc
        style: form
        explode: false
        allowReserved: false
      deprecated: false
components:
  schemas:
    SupplementalServicesFeed-supplementalServicesFeed_supService:
      type: object
      description: ''
      properties:
        projectLifecycleCosts:
          type: string
        lastModified:
          type: string
          format: timestamp
          example: '2020-01-01 15:00:00'
          readOnly: true
          description: Last modified date/time
        agencyCode:
          type: string
          format: string
          example: 018
          description: The agency code of the user who created the record
        agencyId:
          type: string
          format: alphanumeric
          minLength: 1
          maxLength: 32
          description: A unique identifier for the document provided by the submitting user.
        currentUII:
          type: string
          format: string
          example: 018-000000123
          description: 'The Current UII includes an Agency code and a nine-digit unique identifier.

            Variable information formerly included in the UII of previous years is not part

            of the UII primary key.'
        title:
          type: string
          format: string
          example: IT Collect Development
          description: 'This is a text field to provide the Investment title. To the extent that they are not

            part of the name used by the Agency, other identifiers such as bureaus or other

            numeric codes should not be included as part of an Investment title.'
